replicaCount: 1

image:
  repository: nguyengianguit/demo_microservices
  pullPolicy: Always

services:
  front_end:
    name: front-end
    port: 3000
    image: "nguyengianguit/demo_microservices:front-end-latest"


