{{- range $key, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}  # Không thêm $.Release.Name
spec:
  selector:
    app: {{ $service.name }}  # Giữ nguyên tên service trong selector
  ports:
    - protocol: TCP
      port: {{ $service.port }}
      targetPort: {{ $service.port }}
      {{- if eq $service.name "front-end" }}
      nodePort: 30000
      {{- end }}
  {{- if eq $service.name "front-end" }}
  type: NodePort
  {{- else }}
  type: ClusterIP  # Các dịch vụ khác sẽ là ClusterIP
  {{- end }}
{{- end }}

