apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP
